### PR TITLE
add codespell workflow from bids-validator

### PR DESCRIPTION
**Pull request by yarikoptic**
codespell finds plenty of typos but want to see if action works and finds them by default in .ipynb

### CODE REVIEW

**Comment by yarikoptic** [comment]
hm, and now it doesn't run it at all... let's rewrite again

**Comment by yarikoptic** [comment]
jesus christ - why it gets into `.git/`?
```
Resulting CLI options  --skip *.svg
Warning: WARNING: Decoding file using encoding=utf-8 failed: ./.git/objects/1e/a4a450299271c0a5e69bc79e1cb4a8771b34da
Error: ./.git/objects/1e/a4a450299271c0a5e69bc79e1cb4a8771b34da:755: ot ==> to, of, or, not
WARNING: Trying next encoding iso-8859-1
Warning: WARNING: Decoding file using encoding=utf-8 failed: ./.git/objects/78/f14c2775affc5ed4fcd819b66ff5bfd[15](https://github.com/datalad/tutorials/actions/runs/3696668759/jobs/6260675265#step:4:16)92806
WARNING: Trying next encoding iso-8859-1
Warning: WARNING: Decoding file using encoding=utf-8 failed: ./.git/objects/fb/52afd8fb6f45744569797c8ef1d1b7b1dbace0
WARNING: Trying next encoding iso-8859-1
3
Error: ./.git/objects/1e/a4a450299271c0a5e69bc79e1cb4a8771b34da:838: Te ==> The, Be, We, To
Error: ./.git/objects/1e/a4a450299271c0a5e69bc79e1cb4a8771b34da:911: nd ==> and, 2nd
Codespell found one or more problems
```

filed: https://github.com/codespell-project/actions-codespell/issues/56

**Review by jsheunis — APPROVED** [review]
Thanks @yarikoptic this is a handy workflow :) After your additions for skipping svg, git, etc, it all looks good.

**Comment by yarikoptic** [comment]
ok, let's proceed then -- world can only become better right? ;)

**Pull request merged**
