### PR TITLE
DOC: Increase introduction notebook consistency

### PR DESCRIPTION
**Pull request by jhlegarreta**
Increase the introduction notebook consistency:
- Fix misspellings and grammar errors.
- Consistently use the straight tick to mark contractions.
- Highlight the syntax for DataLad commands, and the other special names, such as the folders used to illustrate the cases.
- Use consistently the same case to name `DataLad`.
- Capitalize letters consistently (e.g. `Git`, `GitHub`, etc.) where appropriate.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
A few notes:
- Some of the `git log` commands show not only the commit messages, but the changes as well (`-p`). Is this intended?
- The mentions to the sections `yoda` `YODA` principles, `containersun`, or `chapter_run` and `chapter_gitannex` do not link to anywehere, so they seem a little bit out of context.
- When I noticed that a block appeared to have been limited to 80, 90 char length, I assumed it was intended and stuck to it in the changes.

**Review by adswa — APPROVED** [review]
Thanks a lot for the thorough fixes! I'll leave my approval, but wait with a merge until @jsheunis has had a chance to take a look as well.

**Review by jsheunis — APPROVED** [review]
@jhlegarreta thanks so much for the thorough fixes! Looks good to me!

**Comment by jhlegarreta** [comment]
You're welcome. Thanks for having built/maintaining the tool. Let me know if you have some thoughts about the first 2 comments in https://github.com/datalad/tutorials/pull/19#issuecomment-1349799929 so that I can propose a PR.

**Comment by jsheunis** [comment]
Sorry I missed that 🙈 

This notebook that you helped to improve was originally copied and translated from [this chapter of the handbook](https://handbook.datalad.org/en/latest/code_from_chapters/OHBM.html). This would explain some errors if link text was copied over but the links never updated to point to the full URL (instead of the relative links used in the sphinx docs).

Regarding your comments:

> Some of the git log commands show not only the commit messages, but the changes as well (-p). Is this intended?

I think this is intended and can stay as is.

> The mentions to the sections yoda YODA principles, containersun, or chapter_run and chapter_gitannex do not link to anywehere, so they seem a little bit out of context.

These links should indeed be added, pointing to chapters of the handbook. If you feel like doing this, please go ahead, but no pressure :)

> When I noticed that a block appeared to have been limited to 80, 90 char length, I assumed it was intended and stuck to it in the changes

This would probably code formatting in the sphinx docs according to an adjusted PEP-8. Keeping your additions in line with that is perfect.

**Comment by jhlegarreta** [comment]
:+1:

> These links should indeed be added, pointing to chapters of the handbook. If you feel like doing this, please go ahead, but no pressure :)

See PR #21.

> This notebook that you helped to improve was originally copied and translated from [this chapter of the handbook](https://handbook.datalad.org/en/latest/code_from_chapters/OHBM.html).

OK, maybe someone will have the bandwidth to port the changes I made to the notebook in this PR to the handbook so that they are consistent :-S.

**Pull request merged**
